services:
  webhook-app:
    build: ./node-app
    container_name: webhook-app-js
    expose:
      - "3000"
    networks:
      - app-network

    volumes:
      - ./node-app/allowlist.json:/app/allowlist.json
    restart: unless-stopped

networks:
  app-network:
    external: true