services:
  webhook-app:
    build: ./node-app
    container_name: webhook-app-js
    ports:
      - "3000:3000"
    volumes:
      - ./node-app/allowlist.json:/app/allowlist.json
    restart: unless-stopped